<a href="https://colab.research.google.com/github/sidhantmaurya/machine-learning-algos/blob/main/hyperparameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [6]:
from sklearn.datasets import fetch_openml

data = fetch_openml(name="boston", version=1)

In [10]:
data = pd.DataFrame(df.data)
data.columns = df.feature_names

data.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222.0,18.7,394.12,5.21
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311.0,15.2,395.60,12.43
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311.0,15.2,396.90,19.15
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311.0,15.2,386.71,17.10

In [12]:
data.shape

(506, 13)

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    category
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    category
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: category(2), float64(11)
memory usage: 45.1 KB

In [14]:
x= data.iloc[:,:-1]
y= data.iloc[:,-1]

In [15]:
from sklearn.model_selection import cross_val_score,KFold
from sklearn.neighbors import KNeighborsRegressor

In [16]:
knn=KNeighborsRegressor()

In [17]:
kfold=KFold(n_splits=5, shuffle=True, random_state=1)
score = cross_val_score(knn,x,y, cv=kfold, scoring='r2')

In [19]:
score.mean()

np.float64(0.4671070520237299)

gridsearchCV

In [20]:
from sklearn.model_selection import GridSearchCV

In [21]:
knn = KNeighborsRegressor()

In [22]:
param_grid = {
    'n_neighbors': [1,3,5,7,10,12,15,17,20],
    'weights': ['uniform','distance'],
    'algorithm':['ball_tree', 'kd_tree','brute'],
    'p':[1,2]
}

In [23]:
gcv = GridSearchCV(knn, param_grid,scoring='r2',refit=True, cv=kfold, verbose=2)

In [24]:
gcv.fit(x,y)

Fitting 5 folds for each of 108 candidates, totalling 540 fits
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.1s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s

GridSearchCV(cv=KFold(n_splits=5, random_state=1, shuffle=True),
             estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 3, 5, 7, 10, 12, 15, 17, 20],
                         'p': [1, 2], 'weights': ['uniform', 'distance']},
             scoring='r2', verbose=2)

In [26]:
gcv.best_params_

{'algorithm': 'ball_tree', 'n_neighbors': 10, 'p': 1, 'weights': 'distance'}

In [27]:
gcv.best_score_

np.float64(0.5515393409554453)

In [28]:
gcv.cv_results_

{'mean_fit_time': array([0.01640368, 0.00982966, 0.00596595, 0.00562391, 0.00788298,
        0.00793257, 0.00281844, 0.00308151, 0.00284324, 0.00279694,
        0.00285869, 0.00339446, 0.00455108, 0.0099791 , 0.00709004,
        0.00467219, 0.00900626, 0.01042624, 0.00863128, 0.00485497,
        0.00632057, 0.00559969, 0.0048039 , 0.00515537, 0.00462689,
        0.00874982, 0.00867338, 0.00707922, 0.00495758, 0.00694098,
        0.00513082, 0.00514455, 0.00495391, 0.01410441, 0.01635404,
        0.00477347, 0.00281944, 0.00284343, 0.00285192, 0.00289001,
        0.00391235, 0.00290899, 0.00364428, 0.00329418, 0.00336013,
        0.00294895, 0.00383248, 0.00284677, 0.00280695, 0.00278177,
        0.00280995, 0.00283108, 0.00292001, 0.00279851, 0.00293145,
        0.00281658, 0.00309443, 0.00280261, 0.0029696 , 0.00283747,
        0.00286908, 0.00352626, 0.00281043, 0.00278907, 0.00324655,
        0.00314398, 0.00281715, 0.00287366, 0.00283995, 0.00310068,
        0.00305977, 0.0030283 , 0.00222869, 0.00300131, 0.00251837,
        0.00238695, 0.00239286, 0.00216918, 0.0021637 , 0.00217934,
        0.00217557, 0.00229287, 0.00221353, 0.00245728, 0.00241427,
        0.00245504, 0.00223341, 0.00219464, 0.00216475, 0.00259647,
        0.00218325, 0.00225754, 0.00219741, 0.00216737, 0.00218658,
        0.00232821, 0.0022994 , 0.00220141, 0.00217652, 0.00264258,
        0.00216494, 0.00249205, 0.00234079, 0.00216398, 0.00217991,
        0.00329108, 0.00218425, 0.00216999]),
 'std_fit_time': array([6.72881810e-03, 6.00686188e-03, 5.68578496e-04, 3.16709325e-04,
        2.19409034e-03, 3.10209375e-03, 3.83314797e-05, 4.95386704e-04,
        7.83431407e-05, 4.23670285e-05, 4.89961260e-05, 4.84007581e-04,
        6.23899879e-04, 5.58238166e-03, 2.32013456e-03, 1.17006220e-04,
        2.04108409e-03, 2.88674534e-03, 3.23422306e-03, 5.73128519e-04,
        3.53001668e-03, 1.29366602e-03, 5.42837628e-04, 8.06461893e-04,
        6.09140760e-05, 4.68011509e-03, 2.81665810e-03, 4.99968955e-03,
        3.32807319e-04, 2.49141615e-03, 7.94090384e-04, 8.18849815e-04,
        6.74730129e-04, 3.13431432e-03, 6.74145178e-03, 3.91763039e-03,
        3.38065775e-05, 1.46144171e-05, 1.03118767e-04, 1.57795034e-04,
        1.68916833e-03, 7.97877526e-05, 7.83481040e-04, 7.95417428e-04,
        6.73739243e-04, 2.23477374e-04, 5.73171347e-04, 3.99814238e-05,
        2.17311178e-05, 5.75493263e-06, 1.79555626e-05, 2.53848506e-05,
        2.22249784e-04, 1.99026826e-05, 1.06188712e-04, 1.74137640e-05,
        2.32544052e-04, 1.98961697e-05, 3.43569515e-04, 1.05321380e-04,
        1.26514109e-04, 5.95333921e-04, 2.80627479e-05, 2.84206147e-05,
        8.29397071e-04, 3.58155605e-04, 3.27674224e-05, 1.34061561e-04,
        3.29005891e-05, 2.36967698e-04, 2.47551130e-04, 2.21677005e-04,
        1.44997971e-04, 6.51424022e-04, 5.70075652e-04, 2.01275534e-04,
        4.36212201e-04, 1.23990498e-05, 2.83212371e-05, 4.09997887e-05,
        3.12679399e-05, 1.45422591e-04, 4.30783250e-05, 3.40790870e-04,
        1.47790706e-04, 2.44741585e-04, 3.59301149e-05, 5.19739378e-05,
        1.31710675e-05, 6.64335590e-04, 2.52049825e-05, 4.59088950e-05,
        4.72520362e-05, 1.60103712e-05, 2.51639036e-05, 2.92935446e-04,
        2.80136599e-04, 5.38147440e-05, 3.86558800e-05, 2.69513255e-04,
        1.45771857e-05, 5.50624673e-04, 2.94244925e-04, 2.07693101e-05,
        1.05545942e-05, 4.94024753e-04, 3.33699488e-05, 3.42529095e-05]),
 'mean_score_time': array([0.02075977, 0.00866451, 0.00579839, 0.00524616, 0.01053567,
        0.00644941, 0.00283446, 0.00313811, 0.00302296, 0.00303917,
        0.00294604, 0.0034853 , 0.00510721, 0.00981779, 0.00735531,
        0.00567918, 0.00875425, 0.01122365, 0.00848641, 0.00594869,
        0.00683002, 0.00522695, 0.00476284, 0.00640411, 0.0066299 ,
        0.00768552, 0.00848451, 0.00632544, 0.00636401, 0.00667372,
        0.00609236, 0.00513124, 0.00608859, 0.01639528, 0.01845894,
        0.00335259, 0.00272708, 0.00278368, 0.00266352, 0.00291305,
        0.00323653, 0.00297036, 0.00370388, 0.00313516, 0.00337334,
        0.00331764, 0.003479  , 0.00282063, 0.00291882, 0.0030158 ,
        0.00282373, 0.00286789, 0.00321832, 0.00303159, 0.00313425,
        0.00297418, 0.00411263, 0.00306196, 0.00306668, 0.00318279,
        0.00316353, 0.0033041 , 0.00301189, 0.00299735, 0.00372114,
        0.00342121, 0.00298514, 0.00310674, 0.00335603, 0.00353756,
        0.00346155, 0.00312576, 0.00452867, 0.00505352, 0.00422854,
        0.00385933, 0.0038198 , 0.00359774, 0.00349889, 0.00354095,
        0.00356503, 0.00378556, 0.00358415, 0.00400653, 0.00393524,
        0.00397534, 0.00361943, 0.00358791, 0.00359297, 0.00420647,
        0.00360503, 0.00409393, 0.00360918, 0.00363002, 0.00358586,
        0.00386381, 0.00371099, 0.00363412, 0.00350475, 0.0043622 ,
        0.00360389, 0.00418286, 0.00393195, 0.00360494, 0.00363154,
        0.00561609, 0.00361476, 0.00360713]),
 'std_score_time': array([6.57617974e-03, 4.68109153e-03, 1.19787473e-04, 3.04211643e-04,
        3.04286943e-03, 2.64643894e-03, 3.41761536e-05, 3.96954130e-04,
        5.80364693e-05, 2.35078301e-05, 7.16339879e-05, 5.08482713e-04,
        1.58438530e-04, 5.16772427e-03, 3.12470896e-03, 1.68310997e-03,
        3.30786672e-03, 4.04104753e-03, 3.04873342e-03, 2.35505297e-03,
        2.73830612e-03, 4.16225979e-04, 1.31329939e-04, 2.29457126e-03,
        2.81975878e-03, 2.35564100e-03, 2.86012224e-03, 2.30541084e-03,
        1.89682120e-03, 1.57388117e-03, 1.53824427e-03, 6.55482010e-05,
        1.47073395e-03, 1.72580359e-03, 3.14552374e-03, 2.16791873e-04,
        4.37567664e-05, 6.15132132e-05, 1.17677440e-04, 2.74281086e-04,
        4.03161996e-04, 1.23983035e-04, 8.07010023e-04, 5.82054660e-04,
        5.20748147e-04, 7.51014186e-04, 4.70098347e-04, 2.58538979e-05,
        2.40094020e-05, 7.30565881e-05, 1.06864729e-05, 2.88568832e-05,
        3.07143158e-04, 3.57092138e-05, 4.19977856e-04, 1.23744764e-04,
        1.75117338e-03, 2.07812395e-05, 3.45330086e-04, 5.13700957e-04,
        9.03479207e-05, 1.03817711e-04, 1.15938658e-04, 1.26702372e-05,
        6.13465498e-04, 2.54430522e-04, 3.64621757e-05, 9.48816803e-05,
        1.42210189e-04, 3.11742174e-04, 4.39428724e-04, 7.21482511e-05,
        1.90014115e-03, 1.15120380e-03, 1.19690788e-03, 4.26188463e-04,
        2.05252039e-04, 3.75658717e-05, 5.93239086e-05, 2.02301501e-05,
        3.16970843e-05, 2.35491494e-04, 5.46414605e-05, 5.51828742e-04,
        1.63427517e-04, 1.86872196e-04, 6.19981832e-05, 2.76443849e-05,
        4.27670034e-05, 6.03668882e-04, 4.44202926e-05, 5.16744017e-04,
        1.99594944e-05, 4.02670841e-05, 6.27220150e-05, 5.30882491e-04,
        2.22983097e-04, 1.69954824e-05, 3.05722908e-05, 8.26617295e-04,
        4.57811850e-05, 8.34366035e-04, 5.33337862e-04, 4.17098705e-05,
        2.38506301e-05, 1.59953312e-03, 4.98673646e-05, 2.08665161e-05]),
 'param_algorithm': masked_array(data=['ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[1, 1, 1, 1, 3, 3, 3, 3, 5, 5, 5, 5, 7, 7, 7, 7, 10, 10,
                    10, 10, 12, 12, 12, 12, 15, 15, 15, 15, 17, 17, 17, 17,
                    20, 20, 20, 20, 1, 1, 1, 1, 3, 3, 3, 3, 5, 5, 5, 5, 7,
                    7, 7, 7, 10, 10, 10, 10, 12, 12, 12, 12, 15, 15, 15,
                    15, 17, 17, 17, 17, 20, 20, 20, 20, 1, 1, 1, 1, 3, 3,
                    3, 3, 5, 5, 5, 5, 7, 7, 7, 7, 10, 10, 10, 10, 12, 12,
                    12, 12, 15, 15, 15, 15, 17, 17, 17, 17, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_p': masked_array(data=[1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1,
                    2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2,
                    1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1,
                    2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2,
                    1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1,
                    2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'algorithm': 'ball_tree',
   'n_neighbors': 1,
   'p': 1,
   'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 1, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 1, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 1, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 3, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 3, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 3, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 3, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 10, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 10, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 10, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 10, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 12, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 12, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 12, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 12, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 15, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 15, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 15, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 15, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 17, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 17, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 17, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 17, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 20, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 20, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 20, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 20, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 1, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 1, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 1, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 1, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 3, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 3, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 3, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 3, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 10, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 10, 'p': 1, 'weights': 'distance'},

In [29]:
pd.DataFrame(gcv.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.016404,0.006729,0.020760,0.006576,ball_tree,1,1,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 1, '...",0.251925,0.446106,0.467672,0.294893,0.313094,0.354738,0.086010,97
1,0.009830,0.006007,0.008665,0.004681,ball_tree,1,1,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 1, '...",0.251925,0.446106,0.467672,0.294893,0.313094,0.354738,0.086010,100
2,0.005966,0.000569,0.005798,0.000120,ball_tree,1,2,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 1, '...",0.123084,0.242131,0.466278,0.239905,0.225509,0.259381,0.112434,103
3,0.005624,0.000317,0.005246,0.000304,ball_tree,1,2,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 1, '...",0.123084,0.242131,0.466278,0.239905,0.225509,0.259381,0.112434,103
4,0.007883,0.002194,0.010536,0.003043,ball_tree,3,1,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 3, '...",0.463663,0.544639,0.546918,0.469094,0.571048,0.519072,0.044042,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,0.002164,0.000021,0.003605,0.000042,brute,17,2,distance,"{'algorithm': 'brute', 'n_neighbors': 17, 'p':...",0.437120,0.552831,0.537898,0.460532,0.541609,0.505998,0.047519,40
104,0.002180,0.000011,0.003632,0.000024,brute,20,1,uniform,"{'algorithm': 'brute', 'n_neighbors': 20, 'p':...",0.424419,0.509980,0.468812,0.493511,0.477153,0.474775,0.028870,70
105,0.003291,0.000494,0.005616,0.001600,brute,20,1,distance,"{'algorithm': 'brute', 'n_neighbors': 20, 'p':...",0.478299,0.584772,0.558966,0.508789,0.568295,0.539824,0.039864,16
106,0.002184,0.000033,0.003615,0.000050,brute,20,2,uniform,"{'algorithm': 'brute', 'n_neighbors': 20, 'p':...",0.404768,0.491993,0.465627,0.481060,0.450675,0.458825,0.030428,88
107,0.002170,0.000034,0.003607,0.000021,brute,20,2,distance,"{'algorithm': 'brute', 'n_neighbors': 20, 'p':...",0.439162,0.560706,0.532012,0.476729,0.534755,0.508673,0.044237,28

Randomised search cv

In [30]:
from sklearn.model_selection import RandomizedSearchCV

In [31]:
rcv = RandomizedSearchCV(knn, param_grid, scoring='r2', refit=True, cv=kfold, verbose=2)

In [32]:
rcv.fit(x,y)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s

RandomizedSearchCV(cv=KFold(n_splits=5, random_state=1, shuffle=True),
                   estimator=KNeighborsRegressor(),
                   param_distributions={'algorithm': ['ball_tree', 'kd_tree',
                                                      'brute'],
                                        'n_neighbors': [1, 3, 5, 7, 10, 12, 15,
                                                        17, 20],
                                        'p': [1, 2],
                                        'weights': ['uniform', 'distance']},
                   scoring='r2', verbose=2)

In [33]:
rcv.best_score_

np.float64(0.5441113177349376)

In [34]:
rcv.best_params_

{'weights': 'distance', 'p': 1, 'n_neighbors': 7, 'algorithm': 'ball_tree'}